### ISSUE TITLE
Couple things don't work

### ISSUE THREAD

**Issue by birdybro** [sigboe/MiSTress#1]
On a regular MiSTer install python won't run this because it requires the module "feedparser" to be installed via pip. There is no pip and pip on the mister image, and it cannot be easily installed onto a MiSTer either.

```sh
/media/fat/scripts# mistress.py
Traceback (most recent call last):
  File "/media/fat/Scripts/mistress.py", line 2, in <module>
    import feedparser, sys, os, argparse, locale, ssl, textwrap, time, random
ImportError: No module named 'feedparser'
/media/fat/scripts# curl --insecure https://bootstrap.pypa.io/pip/3.5/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1863k  100 1863k    0     0  4548k      0 --:--:-- --:--:-- --:--:-- 4827k
/media/fat/scripts# python get-pip.py
Traceback (most recent call last):
  File "get-pip.py", line 23974, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
zipimport.ZipImportError: can't decompress data; zlib not available
```

**Comment by sigboe** [comment]
Hello, and thank you for opening this issue. 
You need to in fact download mistress from the [release page](https://github.com/sigboe/MiSTress/releases/latest) there you will get a compiled executable with all the dependencies included. No need to install pip, or anything.

But thank you for bringing to my attention that the readme needs to be more clear on this, I will fix it this evening as well.

**Comment by birdybro** [comment]
Ah, interesting. For some reason I missed it, I usually am good about checking releases, but noticed it was a python script so that's probably why It slipped my mind.

Thanks!
